[tasks.build]
description = "Build Common"
run = "pnpm tsc --build && echo 'packages/common build'"
sources = ["package.json", "tsconfig.json", "src/**/*.ts"]
outputs = ["{{env.common_dist}}"]

[tasks.dev]
description = "Prepare assets"
run = "pnpm tsc --build --watch"

[tasks.clean]
description = "Clean dist files"
run = "rm -rf ./dist"

